// <auto-generated />
using System;
using Catalogue.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalogue.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    partial class CatalogueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalogue.Domain.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WikiLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WikiLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestedCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequestedItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    // optimistic concurrency on the postgres system column —
                    // exists on every row, so no migration DDL accompanies it
                    b.Property<uint>("xmin")
                        .HasColumnType("xid")
                        .IsRowVersion();

                    b.HasIndex("AuthorId");

                    b.HasIndex("RequestedCurrencyId");

                    b.HasIndex("RequestedItemId");

                    b.HasIndex("AuthorId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" <> ''");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("Listings", null, t =>
                        {
                            t.HasCheckConstraint("ck_listings_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("ck_listings_requested_xor", "CAST((\"RequestedItemId\" IS NOT NULL) AS INT) + CAST((\"RequestedCurrencyId\" IS NOT NULL) AS INT) = 1");
                        });
                });

            modelBuilder.Entity("Catalogue.Domain.ListingOfferedCurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ListingId");

                    b.ToTable("OfferedCurrencies", null, t =>
                        {
                            t.HasCheckConstraint("ck_offered_currencies_amount_positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Catalogue.Domain.ListingOfferedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ListingId");

                    b.ToTable("OfferedItems", null, t =>
                        {
                            t.HasCheckConstraint("ck_offered_items_amount_positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Catalogue.Domain.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt")
                        .HasFilter("\"PublishedAt\" IS NULL");

                    b.ToTable("Outbox", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcceptedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("ListingId");

                    b.HasIndex("SellerId");

                    b.HasIndex("AcceptedById", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" <> ''");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.UserItemList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ListType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ListType");

                    b.HasIndex("UserId", "ListType", "CurrencyId")
                        .IsUnique()
                        .HasFilter("\"CurrencyId\" IS NOT NULL");

                    b.HasIndex("UserId", "ListType", "ItemId")
                        .IsUnique()
                        .HasFilter("\"ItemId\" IS NOT NULL");

                    b.ToTable("UserItemLists", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_item_lists_xor", "CAST((\"ItemId\" IS NOT NULL) AS INT) + CAST((\"CurrencyId\" IS NOT NULL) AS INT) = 1");
                        });
                });

            modelBuilder.Entity("Catalogue.Domain.WatchlistEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("Watchlist", (string)null);
                });

            modelBuilder.Entity("Catalogue.Domain.Item", b =>
                {
                    b.HasOne("Catalogue.Domain.ItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Catalogue.Domain.Listing", b =>
                {
                    b.HasOne("Catalogue.Domain.Currency", "RequestedCurrency")
                        .WithMany()
                        .HasForeignKey("RequestedCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Catalogue.Domain.Item", "RequestedItem")
                        .WithMany()
                        .HasForeignKey("RequestedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequestedCurrency");

                    b.Navigation("RequestedItem");
                });

            modelBuilder.Entity("Catalogue.Domain.ListingOfferedCurrency", b =>
                {
                    b.HasOne("Catalogue.Domain.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catalogue.Domain.Listing", "Listing")
                        .WithMany("OfferedCurrencies")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Catalogue.Domain.ListingOfferedItem", b =>
                {
                    b.HasOne("Catalogue.Domain.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catalogue.Domain.Listing", "Listing")
                        .WithMany("OfferedItems")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Catalogue.Domain.Trade", b =>
                {
                    b.HasOne("Catalogue.Domain.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalogue.Domain.WatchlistEntry", b =>
                {
                    b.HasOne("Catalogue.Domain.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Catalogue.Domain.Listing", b =>
                {
                    b.Navigation("OfferedCurrencies");

                    b.Navigation("OfferedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
