// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/openmarket/auth/v1/auth.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Catalogue.AuthGrpc {
  /// <summary>
  /// Internal identity lookups for the gateway's BFF aggregation.
  /// Auth owns the data; the gateway borrows it per request, never stores it.
  /// </summary>
  public static partial class AuthService
  {
    static readonly string __ServiceName = "openmarket.auth.v1.AuthService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Catalogue.AuthGrpc.GetUserRequest> __Marshaller_openmarket_auth_v1_GetUserRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Catalogue.AuthGrpc.GetUserRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Catalogue.AuthGrpc.GetUserResponse> __Marshaller_openmarket_auth_v1_GetUserResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Catalogue.AuthGrpc.GetUserResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Catalogue.AuthGrpc.IntrospectTokenRequest> __Marshaller_openmarket_auth_v1_IntrospectTokenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Catalogue.AuthGrpc.IntrospectTokenRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Catalogue.AuthGrpc.IntrospectTokenResponse> __Marshaller_openmarket_auth_v1_IntrospectTokenResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Catalogue.AuthGrpc.IntrospectTokenResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Catalogue.AuthGrpc.GetUserRequest, global::Catalogue.AuthGrpc.GetUserResponse> __Method_GetUser = new grpc::Method<global::Catalogue.AuthGrpc.GetUserRequest, global::Catalogue.AuthGrpc.GetUserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUser",
        __Marshaller_openmarket_auth_v1_GetUserRequest,
        __Marshaller_openmarket_auth_v1_GetUserResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Catalogue.AuthGrpc.IntrospectTokenRequest, global::Catalogue.AuthGrpc.IntrospectTokenResponse> __Method_IntrospectToken = new grpc::Method<global::Catalogue.AuthGrpc.IntrospectTokenRequest, global::Catalogue.AuthGrpc.IntrospectTokenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "IntrospectToken",
        __Marshaller_openmarket_auth_v1_IntrospectTokenRequest,
        __Marshaller_openmarket_auth_v1_IntrospectTokenResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Catalogue.AuthGrpc.AuthReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AuthService</summary>
    [grpc::BindServiceMethod(typeof(AuthService), "BindService")]
    public abstract partial class AuthServiceBase
    {
      /// <summary>
      /// Resolve a user by id — reserved for the gateway's future BFF
      /// aggregations (not implemented on the server yet: answers UNIMPLEMENTED).
      /// Unknown or soft-deleted users return NOT_FOUND.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Catalogue.AuthGrpc.GetUserResponse> GetUser(global::Catalogue.AuthGrpc.GetUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Validate an access token for the gateway's auth middleware. Returns the
      /// token's validity AND the account's live state — soft-deleted or banned
      /// accounts report active=false even while their token is cryptographically
      /// valid (signature checks cannot see database state). Invalid, expired or
      /// malformed tokens also report active=false; infrastructure failures
      /// surface as gRPC Unavailable instead, so callers can 503 rather than 401.
      /// NOTE: the gateway caches verdicts briefly (10s TTL), and auth's protected
      /// REST routes re-validate tokens cryptographically only — ban enforcement
      /// happens here (plus at login/refresh), so a fresh ban reaches the edge
      /// within the cache TTL, not instantly.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Catalogue.AuthGrpc.IntrospectTokenResponse> IntrospectToken(global::Catalogue.AuthGrpc.IntrospectTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AuthService</summary>
    public partial class AuthServiceClient : grpc::ClientBase<AuthServiceClient>
    {
      /// <summary>Creates a new client for AuthService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AuthServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AuthService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AuthServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AuthServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AuthServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Resolve a user by id — reserved for the gateway's future BFF
      /// aggregations (not implemented on the server yet: answers UNIMPLEMENTED).
      /// Unknown or soft-deleted users return NOT_FOUND.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Catalogue.AuthGrpc.GetUserResponse GetUser(global::Catalogue.AuthGrpc.GetUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Resolve a user by id — reserved for the gateway's future BFF
      /// aggregations (not implemented on the server yet: answers UNIMPLEMENTED).
      /// Unknown or soft-deleted users return NOT_FOUND.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Catalogue.AuthGrpc.GetUserResponse GetUser(global::Catalogue.AuthGrpc.GetUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUser, null, options, request);
      }
      /// <summary>
      /// Resolve a user by id — reserved for the gateway's future BFF
      /// aggregations (not implemented on the server yet: answers UNIMPLEMENTED).
      /// Unknown or soft-deleted users return NOT_FOUND.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Catalogue.AuthGrpc.GetUserResponse> GetUserAsync(global::Catalogue.AuthGrpc.GetUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Resolve a user by id — reserved for the gateway's future BFF
      /// aggregations (not implemented on the server yet: answers UNIMPLEMENTED).
      /// Unknown or soft-deleted users return NOT_FOUND.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Catalogue.AuthGrpc.GetUserResponse> GetUserAsync(global::Catalogue.AuthGrpc.GetUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUser, null, options, request);
      }
      /// <summary>
      /// Validate an access token for the gateway's auth middleware. Returns the
      /// token's validity AND the account's live state — soft-deleted or banned
      /// accounts report active=false even while their token is cryptographically
      /// valid (signature checks cannot see database state). Invalid, expired or
      /// malformed tokens also report active=false; infrastructure failures
      /// surface as gRPC Unavailable instead, so callers can 503 rather than 401.
      /// NOTE: the gateway caches verdicts briefly (10s TTL), and auth's protected
      /// REST routes re-validate tokens cryptographically only — ban enforcement
      /// happens here (plus at login/refresh), so a fresh ban reaches the edge
      /// within the cache TTL, not instantly.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Catalogue.AuthGrpc.IntrospectTokenResponse IntrospectToken(global::Catalogue.AuthGrpc.IntrospectTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IntrospectToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Validate an access token for the gateway's auth middleware. Returns the
      /// token's validity AND the account's live state — soft-deleted or banned
      /// accounts report active=false even while their token is cryptographically
      /// valid (signature checks cannot see database state). Invalid, expired or
      /// malformed tokens also report active=false; infrastructure failures
      /// surface as gRPC Unavailable instead, so callers can 503 rather than 401.
      /// NOTE: the gateway caches verdicts briefly (10s TTL), and auth's protected
      /// REST routes re-validate tokens cryptographically only — ban enforcement
      /// happens here (plus at login/refresh), so a fresh ban reaches the edge
      /// within the cache TTL, not instantly.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Catalogue.AuthGrpc.IntrospectTokenResponse IntrospectToken(global::Catalogue.AuthGrpc.IntrospectTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_IntrospectToken, null, options, request);
      }
      /// <summary>
      /// Validate an access token for the gateway's auth middleware. Returns the
      /// token's validity AND the account's live state — soft-deleted or banned
      /// accounts report active=false even while their token is cryptographically
      /// valid (signature checks cannot see database state). Invalid, expired or
      /// malformed tokens also report active=false; infrastructure failures
      /// surface as gRPC Unavailable instead, so callers can 503 rather than 401.
      /// NOTE: the gateway caches verdicts briefly (10s TTL), and auth's protected
      /// REST routes re-validate tokens cryptographically only — ban enforcement
      /// happens here (plus at login/refresh), so a fresh ban reaches the edge
      /// within the cache TTL, not instantly.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Catalogue.AuthGrpc.IntrospectTokenResponse> IntrospectTokenAsync(global::Catalogue.AuthGrpc.IntrospectTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IntrospectTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Validate an access token for the gateway's auth middleware. Returns the
      /// token's validity AND the account's live state — soft-deleted or banned
      /// accounts report active=false even while their token is cryptographically
      /// valid (signature checks cannot see database state). Invalid, expired or
      /// malformed tokens also report active=false; infrastructure failures
      /// surface as gRPC Unavailable instead, so callers can 503 rather than 401.
      /// NOTE: the gateway caches verdicts briefly (10s TTL), and auth's protected
      /// REST routes re-validate tokens cryptographically only — ban enforcement
      /// happens here (plus at login/refresh), so a fresh ban reaches the edge
      /// within the cache TTL, not instantly.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Catalogue.AuthGrpc.IntrospectTokenResponse> IntrospectTokenAsync(global::Catalogue.AuthGrpc.IntrospectTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_IntrospectToken, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AuthServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuthServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AuthServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetUser, serviceImpl.GetUser)
          .AddMethod(__Method_IntrospectToken, serviceImpl.IntrospectToken).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuthServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetUser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Catalogue.AuthGrpc.GetUserRequest, global::Catalogue.AuthGrpc.GetUserResponse>(serviceImpl.GetUser));
      serviceBinder.AddMethod(__Method_IntrospectToken, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Catalogue.AuthGrpc.IntrospectTokenRequest, global::Catalogue.AuthGrpc.IntrospectTokenResponse>(serviceImpl.IntrospectToken));
    }

  }
}
#endregion
