// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/openmarket/auth/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the user (the JWT `sub` claim).
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_openmarket_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	EmailVerified bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	// Role ids (user, moderator, admin, owner) — mirrors the JWT `roles` claim.
	Roles         []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_openmarket_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *GetUserResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type IntrospectTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw access token (JWT) exactly as presented by the client.
	AccessToken   string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectTokenRequest) Reset() {
	*x = IntrospectTokenRequest{}
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectTokenRequest) ProtoMessage() {}

func (x *IntrospectTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectTokenRequest.ProtoReflect.Descriptor instead.
func (*IntrospectTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_openmarket_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *IntrospectTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type IntrospectTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True only when the token is cryptographically valid AND the account is
	// live (not soft-deleted) AND not under an active ban.
	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	// UUID from the JWT `sub` claim; empty when active=false.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Live role ids from the database — fresher than the JWT `roles` claim,
	// which can be up to one access-token TTL stale.
	Roles         []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectTokenResponse) Reset() {
	*x = IntrospectTokenResponse{}
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectTokenResponse) ProtoMessage() {}

func (x *IntrospectTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openmarket_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectTokenResponse.ProtoReflect.Descriptor instead.
func (*IntrospectTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_openmarket_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *IntrospectTokenResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntrospectTokenResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_proto_openmarket_auth_v1_auth_proto protoreflect.FileDescriptor

const file_proto_openmarket_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"#proto/openmarket/auth/v1/auth.proto\x12\x12openmarket.auth.v1\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x88\x01\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\";\n" +
	"\x16IntrospectTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"`\n" +
	"\x17IntrospectTokenResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles2\xcd\x01\n" +
	"\vAuthService\x12R\n" +
	"\aGetUser\x12\".openmarket.auth.v1.GetUserRequest\x1a#.openmarket.auth.v1.GetUserResponse\x12j\n" +
	"\x0fIntrospectToken\x12*.openmarket.auth.v1.IntrospectTokenRequest\x1a+.openmarket.auth.v1.IntrospectTokenResponseB\x86\x01\n" +
	"\x1fdev.bob.openmarket.auth.grpc.v1B\x10AuthServiceProtoP\x01Z:github.com/openmarket-corpo/gateway/internal/authpb;authpb\xaa\x02\x12Catalogue.AuthGrpcb\x06proto3"

var (
	file_proto_openmarket_auth_v1_auth_proto_rawDescOnce sync.Once
	file_proto_openmarket_auth_v1_auth_proto_rawDescData []byte
)

func file_proto_openmarket_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_openmarket_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_openmarket_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openmarket_auth_v1_auth_proto_rawDesc), len(file_proto_openmarket_auth_v1_auth_proto_rawDesc)))
	})
	return file_proto_openmarket_auth_v1_auth_proto_rawDescData
}

var file_proto_openmarket_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_openmarket_auth_v1_auth_proto_goTypes = []any{
	(*GetUserRequest)(nil),          // 0: openmarket.auth.v1.GetUserRequest
	(*GetUserResponse)(nil),         // 1: openmarket.auth.v1.GetUserResponse
	(*IntrospectTokenRequest)(nil),  // 2: openmarket.auth.v1.IntrospectTokenRequest
	(*IntrospectTokenResponse)(nil), // 3: openmarket.auth.v1.IntrospectTokenResponse
}
var file_proto_openmarket_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: openmarket.auth.v1.AuthService.GetUser:input_type -> openmarket.auth.v1.GetUserRequest
	2, // 1: openmarket.auth.v1.AuthService.IntrospectToken:input_type -> openmarket.auth.v1.IntrospectTokenRequest
	1, // 2: openmarket.auth.v1.AuthService.GetUser:output_type -> openmarket.auth.v1.GetUserResponse
	3, // 3: openmarket.auth.v1.AuthService.IntrospectToken:output_type -> openmarket.auth.v1.IntrospectTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_openmarket_auth_v1_auth_proto_init() }
func file_proto_openmarket_auth_v1_auth_proto_init() {
	if File_proto_openmarket_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openmarket_auth_v1_auth_proto_rawDesc), len(file_proto_openmarket_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_openmarket_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_openmarket_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_openmarket_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_openmarket_auth_v1_auth_proto = out.File
	file_proto_openmarket_auth_v1_auth_proto_goTypes = nil
	file_proto_openmarket_auth_v1_auth_proto_depIdxs = nil
}
